analyzers:
        motors:
                type: diagnostic_aggregator/GenericAnalyzer
                path: Motors
                startswith: 'Motor'
                find_and_remove_prefix: motor
        reset:
                type: diagnostic_aggregator/GenericAnalyzer
                path: Reset
                startswith: 'Reset'
                timeout: -1
        voltage:
                type: diagnostic_aggregator/GenericAnalyzer
                path: Voltage
                startswith: 'Voltage'
