TrajectoryPlannerROS:
  min_vel_x: 0.2
  max_vel_x: 0.5
  min_vel_theta: -1.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  max_rotational_vel: 1.0 # used by rotate recovery

  acc_lim_x: 10.07
  acc_lim_y: 0.0
  acc_lim_theta: 6.00

  holonomic_robot: false
  # gdist_scale and pdist_scale parameters should assume meters
  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1

  # The weighting for how much the controller should attempt to avoid obstacles, default: 0.01
  occdist_scale: 0.02

  # Whether to score based on the robot's heading to the path or its distance from the path, default: false
  heading_scoring: false

  # How far to look ahead in time in seconds along the simulated trajectory when using heading scoring, default: 0.1
  heading_scoring_timestep: 0.3

  # How far the robot must travel in meters before oscillation flags are reset, default: 0.05
  oscillation_reset_dist: 0.1

DWAPlannerROS:
  acc_lim_x: 10.07
  acc_lim_y: 0.0
  acc_lim_th: 6.00

  max_vel_x: 0.5
  min_vel_x: 0.0 # no backward movement
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.5
  min_trans_vel: 0.2
  max_rot_vel: 1.0
  min_rot_vel: 0.4

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2

  # The weighting for how much the controller should attempt to avoid obstacles, default: 0.01
  occdist_scale: 0.02
  # The weighting for how much the controller should stay close to the path it was given, default: 32.0
  path_distance_bias: 64.0
