TrajectoryPlannerROS:
  min_vel_x: 0.1
  max_vel_x: 0.3
  min_vel_theta: -0.4
  max_vel_theta: 0.4
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.3

  holonomic_robot: false
  meter_scoring: true
