subscribers:
  - name:        "Default input"
    topic:       "/cmd_vel"
    timeout:     0.1
    priority:    0
    short_desc:  "The default cmd_vel, controllers unaware that we are multiplexing cmd_vel should come here"
  - name:        "Navigation stack"
    topic:       "/move_base/cmd_vel"
    timeout:     0.5
    priority:    1
    short_desc:  "Navigation stack controller"
  - name:        "Wii Teleop"
    topic:       "/turtlebot_teleop_joystick/cmd_vel"
    timeout:     0.1
    priority:    10
publisher:       "/cmd_vel_out"
