# must match incoming static map
global_frame: map
robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 5.0
resolution: 0.05

rolling_window: false
track_unknown_space: true

plugins: 
- {name: static_layer, type: 'costmap_2d::StaticLayer'}
- {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
# Can disable sensor layer if gmapping is fast enough to update scans
- {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
- {name: range_layer,   type: "range_sensor_layer::RangeSensorLayer"}
- {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

static_layer:
  # Can pull data from gmapping, map_server or a non-rolling costmap
  map_topic: /map
  # map_topic: move_base/global_costmap/costmap
  subscribe_to_updates: true

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: middle
  # set to false for gmapping, true if re-exploring a known area
  explore_clear_space: false
