footprint: [[0.14, 0.16], [-0.14, 0.16], [-0.14, -0.16], [0.14, -0.16]]

obstacle_layer:
  observation_sources: laser_scan_sensor
  obstacle_range: 2.5
  raytrace_range: 3.0
  laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.20

range_layer:
  topics: ["/range_forward", "/range_backward", "/range_left", "/range_right"]
  no_readings_timeout: 1.0
  clear_on_max_reading: true
