global_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: true
  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

inflation_layer:
  inflation_radius: 0.25
