local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  #- {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

  sonar_layer:
    topics: ["range_forward", "range_backward", "range_left", "range_right"]
    no_readings_timeout: 1.0
