## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -285
accel_x_max: 280
accel_y_min: -293
accel_y_max: 273
accel_z_min: -298
accel_z_max: 218

### magnetometer
# standard calibration
magn_x_min: -259
magn_x_max: 848
magn_y_min: -448
magn_y_max: 565
magn_z_min: -954
magn_z_max: 150


# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [273.816, 45.5562, -410.533]
magn_ellipsoid_transform: [[0.913987, 0.0421156, 0.0394039], [0.0421156, 0.953725, 0.0238406], [0.0394039, 0.0238406, 0.909422]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -42.24
gyro_average_offset_y: -24.73
gyro_average_offset_z: -21.86
